"""
Django settings for Mgt project.

Generated by 'django-admin startproject' using Django 1.11.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

DEFAULT_AUTO_FIELD='django.db.models.AutoField'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '' #CHANGE add random string

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['0.0.0.0', 'localhost', '127.0.0.1', '[::1]', '*']

INSTALLED_APPS = [
    'django_tables2',
    'Home',
    'Blankdb', #change this to new database app name (normally capitalised first letter)
    'django.contrib.auth',
    'django.contrib.admin',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
	'rest_framework',
	'django_registration',
	'django_countries',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Mgt.urls_template' # CHANGE to new urls filename

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'Home/templates/'), os.path.join(BASE_DIR, 'Home/templates/')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
				'Mgt.context_processors.root_url',
            ],
        },
    },
]

# MY_URL = "http://mgtdb.unsw.edu.au"
MY_URL = "http://127.0.0.1:8000"
WSGI_APPLICATION = 'Mgt.wsgi.application'

FILE_UPLOAD_PERMISSIONS=0o774
FILE_UPLOAD_DIRECTORY_PERMISSIONS=0o774

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

# 2018, Jan 9 - require a db router (if multiple databases)
NCBI_RETRIEVAL_FREQUENCY = {'Blankdb': None}

DATABASE_ROUTERS = ['Mgt.router.GenericRouter']
APPS_DATABASE_MAPPING = {'Blankdb': 'blankdb'} #CHANGE change to appname in INSTALLED_APPS and database DATABASES in name normally upper and lowercase first letter i.e. Salmonella and salmonella

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'HOST': '0.0.0.0',
        'PORT': '5432',
        'USER': 'blankuser', #CHANGE add postgres user
        'PASSWORD': 'blankpassword', #CHANGE add postgres password
        'NAME': 'default',
    },
    'blankdb': { #CHANGE postgres database name
        'ENGINE': 'django.db.backends.postgresql',
        'HOST': '0.0.0.0',
        'PORT': '5432',
        'USER': 'blankuser', #CHANGE add postgres user
        'PASSWORD': 'blankpassword', #CHANGE add postgres password
        'NAME': 'blankdb',#CHANGE to new database name
    }
}

NONLOCALHOST='0.0.0.0' # leave as 0.0.0.0 for local install

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# added_on: 2018, Feb 8 - for HMAC activation workflow
ACCOUNT_ACTIVATION_DAYS = 7 # One-week activation window;
INCLUDE_REGISTER_URL = True
REGISTRATION_OPEN = True
EMAIL_HOST = 'localhost'
EMAIL_PORT = 1025
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
EMAIL_USE_TLS = False
DEFAULT_FROM_EMAIL = 'mgtdb@babs.unsw.edu.au'
LOGIN_REDIRECT_URL = '/'


#RELATIVE PATHS FROM folder containing manage.py in this repo to folder on your system
SUBDIR_REFERENCES = './../../../../References/' #CHANGE location where reference genomes will be stored
SUBDIR_ALLELES = './../../../../Alleles/' #CHANGE location where allele sequences for the database will be stored
MEDIA_ROOT = './../../../../Uploads/'#CHANGE location where uploaded reads/allele files will be stored
BLASTALLELES='./../../../../species_specific_alleles/'#CHANGE location where initial allele sequences will be stored for read2allele

# ABSOLUTE PATH VERSIONS OF ABOVE
ABS_SUBDIR_REFERENCES = '/path/to/References/' #CHANGE location where reference genomes will be stored
ABS_SUBDIR_ALLELES = '/path/to/Alleles/' #CHANGE location where allele sequences for the database will be stored
ABS_MEDIA_ROOT = "/path/to/Uploads/" #CHANGE location where uploaded reads/allele files will be stored
ABS_BLASTALLELES='/path/to/species_specific_alleles/'#CHANGE location where initial allele sequences will be stored for read2allele

FILES_FOR_DOWNLOAD = "/Path/to/folder/files_for_download"#CHANGE replace path with storage location of allele and profile collections
TMPFOLDER = "/Path/to/folder/tmp_files/"#CHANGE replace path with tmp specified in setup script

ASCPKEY = "/Path/to/.aspera/connect/etc/asperaweb_id_dsa.openssh"#CHANGE ONLY NEEDED IF RUNNING cron_pipeline --dl_reads

KRAKEN_DEFAULT_DB='/Path/to/folder/minikraken_20171013_4GB/'#CHANGE ONLY NEEDED IF RUNNING cron_pipeline --reads_to_alleles

### NOT NEEDED ON LOCAL DB ###
KATANA_LOCATION=''
TESTDB="True"
KATANA_SETTINGS=''
##############################

#CHANGE BELOW TO list species specific cutoffs/values
SPECIES_SEROVAR = {'Blankdb': {"species":'Blank species',
                                  "serovar":'',
                                  "min_largest_contig":60000,
                                  "max_contig_no":700,
                                  "n50_min":20000,
                                  "genome_min":4500000,
                                  "genome_max":5500000,
                                  "hspident":0.96,
                                  "locusnlimit":0.8,
                                  "snpwindow":40,
                                  "densitylim":4,
                                  "refsize":5.0,
                                  "blastident":90,
                                  "apzero":0.04
                                  }
                   }

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Australia/Sydney'

USE_I18N = True

USE_L10N = False

USE_TZ = True

DATE_FORMAT = 'Y-m-d'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = 'Static/'
